name: SPRINGBOOT-JAVA-API

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      
      - name: "cloning repo"
        uses: actions/checkout@v4
        with:
          ref: "master"
      
      - name: "setting up java 21"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'pom.xml'
      
      - name: "build with maven"
        run: |
          #!/bin/bash

          mvn package
        shell: bash
      
      - name: "build the docker image"
        run: |
          #!/bin/bash

          docker build -t lingarajsahu49/java:springboot-api .
        shell: bash

      - name: "login to docker hub"
        uses: docker/login-action@v3.4.0
        with:
          username: "lingarajsahu49"
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "upload artifacts to dockerhub"
        run: |
          #!/bin/bash

          docker push lingarajsahu49/java:springboot-api
        shell: bash
